"""Add is_blocked column to User model

Revision ID: 7978d8ee1cd3
Revises: ccaef8040302
Create Date: 2024-11-24 03:15:06.432176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7978d8ee1cd3'
down_revision = 'ccaef8040302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_path', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    with op.batch_alter_table('service_professional', schema=None) as batch_op:
        batch_op.drop_column('resume_path')

    # ### end Alembic commands ###
