"""Add ServiceRequest model

Revision ID: f97a3799021e
Revises: 91e0d5196ac4
Create Date: 2024-11-29 16:52:53.074884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97a3799021e'
down_revision = '91e0d5196ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'service_professional', ['professional_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('professional_id')

    # ### end Alembic commands ###
